apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-production
  name: example-app-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-production
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-production
    spec:
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: production
        - name: APP_IMAGE_DIGEST
          value: sha256:7eb77c17d07882fbcda753f9a3d9e7db52b2c6b35fccb3c856aa299154f1fd77
        image: ghcr.io/get-glu/gitops-example/app@sha256:7eb77c17d07882fbcda753f9a3d9e7db52b2c6b35fccb3c856aa299154f1fd77
        name: container
        ports:
        - containerPort: 8080
        resources: {}
status: {}
